### ISSUE TITLE
Error in python: KeyError

### ISSUE THREAD

**Issue by sijomc** [daamien/mailchimp_fdw#3]
While trying to fetch data from FDW table which shows the below-given error:

datastore_default=# SELECT * from members;
ERROR:  Error in python: KeyError
DETAIL:  'id'

Please help me to fix this issue

**Comment by shanilsasikumar** [comment]
You can solve this issue by defining a new schema in your database. Create a new schema in your database and define your table in it.
EX : 

```
CREATE SCHEMA IF NOT EXISTS mailchimp;

CREATE FOREIGN TABLE mailchimp.members (
	id TEXT,
	email TEXT,
	email_type TEXT,
	merges	TEXT,
	status	TEXT 
) server mailchimp_members_fdw options (
   key 'your_secret_api_key',
   list_name 'your_list_name' 
);
SELECT * FROM mailchimp.members;
```

**Comment by sijomc** [comment]
Thanks @shanilsasikumar

**Comment by daamien** [comment]
thanks a lot @shanilsasikumar
